### ISSUE TITLE
Revise exercises, add notRepeatingRandom where applicable

### ISSUE THREAD

**Issue by Oxoron** [Oxoron/Oxoron.github.io#21]

**Comment by v-aryan** [comment]
Can you please tell me exactly what has to be done ?

**Comment by Oxoron** [comment]
@aryanvarma7272 : please replace .random() calls to the respective .notRepeatingRandom() calls in ToBePresent.html and VocabularyAdjectiveColours.html files.

You may use commits 2cb74eddbbf92b46ce3ccf82771901f35de50dfb or 710c3006abb8e21b3d578126582d2fcef26bc0f0 as a sample.
